---
title: 'A simple example of moltenNMF'
author: "Ko ABE"
date: "9/13/2023"
output: rmarkdown::github_document
---

```{r setup, include=FALSE, fig.width = 14, fig.height = 10, fig.align = "center"}
knitr::opts_chunk$set(echo = TRUE)
```

## Workflow (Titanic data)

Load packages:
```{r library}
if(!any(rownames(installed.packages())=="moltenNMF")){
  devtools::install_github("abikoushi/moltenNMF")
}
library(moltenNMF)
library(dplyr)
library(ggplot2)
library(tidyr)
```

Run `mNMF_vb`:
```{r titanic}
Titanicdf <- as.data.frame(Titanic) %>% 
  mutate(Class=factor(Class,levels=c("3rd","2nd","1st","Crew")))

set.seed(794)
out2 <- mNMF_vb(Freq~Survived+Class+Sex+Age, data=Titanicdf, L=2, iter=500)
```

Check convergence:
```{r titanic2}
plot(out2$ELBO, type = "l", xlab="iter", ylab="ELBO")
```


Check goodness-of-fit:
```{r titanic3}
V <- out2$shape/out2$rate
yhat <- product_m(~Survived+Class+Sex+Age, data=Titanicdf,V)
plot(log1p(yhat), log1p(Titanicdf$Freq), ylab = "fit", xlab = "obs", xlim = c(-0.5,7), ylim=c(-0.5,7))
abline(0, 1, lty=2, col="steelblue")
```


Show parameters $v_{dl}$:
```{r titanic4}
Vdf <- data.frame(V,
                  variable=rownames(V),
                  facet_dummy=out2$vargroup) %>% 
  pivot_longer(!(variable|facet_dummy), names_to = "component", 
               names_transform = list(component = readr::parse_number)) %>% 
  mutate(component=factor(component))

p1 <- ggplot(Vdf, aes(y=variable, x=value, fill=component))+
  geom_col(colour="gray20")+
  facet_grid(facet_dummy~.,scales="free_y", space = "free")+
  theme_classic(16)+theme(strip.text.y = element_text(angle=0))

p2 <- ggplot(Vdf, aes(y=variable, x=value, fill=component))+
  geom_col(colour="gray20", position = "fill")+
  facet_grid(facet_dummy~.,scales="free_y",space = "free")+
  scale_x_continuous(labels=scales::percent)+
  theme_classic(16)+theme(strip.text.y = element_text(angle=0))

p3 <- ggplot(Vdf, aes(y=variable, x=component, fill=log(value)))+
  geom_tile()+
  facet_grid(facet_dummy~.,scales="free_y",space = "free")+
  scale_fill_gradient2(low="royalblue", high="orange", mid="white", midpoint=0)+
  theme_classic(16)+theme(strip.text.y = element_text(angle=0))

print(p1)
print(p2)
print(p3)
```

These plot show co-occurrence relationships between variables. 
You can see that many of survivors of Titanic are women, because of `Survived_Yes`  and `Sex_Female` have large proportion `component 1`.
