---
title: "Simulation study for ordinary NMF"
author: "Ko Abe"
date: "2025-07-25"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(moltenNMF)
library(Matrix)
library(dplyr)
library(ggplot2)
library(tidyr)
```

Setup sythetic data.


```{r setup-data}

set_data_mf <- function(L, nrow, ncol, mu=0){
  W <- matrix(rnorm(nrow*L,0,1), ncol=L)
  H <- matrix(rnorm(L*ncol,0,1), nrow=L)
  W <- sweep(W,1,rowMeans(W)-mu)
  H <- sweep(H,2,colMeans(H)-mu)
  Y <- matrix(rpois(nrow*ncol, exp(W)%*%exp(H)), nrow, ncol)
  Y <- as(Y, "TsparseMatrix")
  list(Y=Y, trueW=W, trueH=H)
}
dat <- set_data_mf(3, 99, 500)
```

```{r, runVB}
system.time({
  out <- moltenNMF:::NMF2D_vb(dat$Y, rank = 3, iter = 1000)
})
```

```{r check-convergence, echo = FALSE}
plot(out$ELBO[-1], type = "l")
V = moltenNMF:::meanV_array(out)
V = moltenNMF:::rearrange_cols(V)

fit1 = V[[1]]%*%t(V[[2]])
p1 = ggplot(data = NULL, aes(x=c(fit1), y=c(as.matrix(dat$Y))))+
  geom_bin2d(aes(fill = after_stat(log10(count))))+
  geom_abline(intercept = 0, slope = 1, linetype=2, colour="grey")
print(p1)
```
```{r plotV, echo = FALSE}
plot(log(V[[1]]), dat$trueW)
plot(log(V[[2]]), t(dat$trueH))
```

```{r runSVB}
system.time({
  out2 <- moltenNMF:::NMF2D_svb(dat$Y, rank = 3,
                                n_epochs = 200, n_baches = as.integer(2000),
                                prior_shape = 1, prior_rate = 1,
                                lr_param = c(15, 0.8),
                                lr_type = "exponential")  
})
```


```{r check-convergence2, echo = FALSE}
plot(out2$ELBO[-1], type = "l")
V = moltenNMF:::meanV_array(out2)
V = moltenNMF:::rearrange_cols(V)

fit1 = V[[1]]%*%t(V[[2]])
p1 = ggplot(data = NULL, aes(x=c(fit1), y=c(as.matrix(dat$Y))))+
  geom_bin2d(aes(fill = after_stat(log10(count))))+
  geom_abline(intercept = 0, slope = 1, linetype=2, colour="grey")
print(p1)
```

```{r plotV2, echo=FALSE}
plot(log(V[[1]]), dat$trueW)
plot(log(V[[2]]), t(dat$trueH))
```