double up_B_sp(const int & N,
             arma::mat & beta,
             arma::mat & V,
             arma::mat & logV,
             arma::vec & gamma_all,
             const int & N0,
             const arma::vec & probx,
             const arma::mat & alpha,
             const arma::uvec & xi,
             const arma::uvec & xp,
             const arma::uvec & varind,
             const double & b);

double up_B_s(const int & N,
               arma::mat & beta,
               arma::mat & V,
               arma::mat & logV,
               arma::vec & gamma_all,
               const double & p0,
               const arma::vec & probx,
               const arma::mat & alpha,
               const arma::uvec & xi,
               const arma::uvec & xp,
               const arma::uvec & varind,
               const double & b);
