void up_B2(const int & N,
           arma::mat & beta,
           arma::mat & V,
           arma::mat & logV,
           const arma::vec & z,
           const arma::mat & alpha,
           const arma::uvec & xi,
           const arma::uvec & xp,
           const arma::uvec & varind,
           const double & b);
