# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_pois <- function(y, xi, xp, varind, D, L, iter, a, b) {
    .Call(`_moltenNMF_doVB_pois`, y, xi, xp, varind, D, L, iter, a, b)
}

doVB_negbin <- function(y, xi, xp, varind, D, L, iter, a, b) {
    .Call(`_moltenNMF_doVB_negbin`, y, xi, xp, varind, D, L, iter, a, b)
}

doVB_pois_missing <- function(y, xi, xp, miss_row, miss_col, sumx, varind, D, L, iter, a, b, eta) {
    .Call(`_moltenNMF_doVB_pois_missing`, y, xi, xp, miss_row, miss_col, sumx, varind, D, L, iter, a, b, eta)
}

myprod <- function(N, xi, xp, lam) {
    .Call(`_moltenNMF_myprod`, N, xi, xp, lam)
}

PoissonGamma_rng <- function(N, np, xi, xp, alpha, beta) {
    .Call(`_moltenNMF_PoissonGamma_rng`, N, np, xi, xp, alpha, beta)
}

NegbinGamma_rng <- function(N, np, xi, xp, alpha, beta, tau) {
    .Call(`_moltenNMF_NegbinGamma_rng`, N, np, xi, xp, alpha, beta, tau)
}

