# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_negbin <- function(y, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_negbin`, y, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois <- function(y, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois`, y, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois_sp <- function(N, yv, yi, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_sp`, N, yv, yi, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois_2D <- function(V, y, rowi, coli, dims, L, iter, a, b, display_progress) {
    .Call(`_moltenNMF_doVB_pois_2D`, V, y, rowi, coli, dims, L, iter, a, b, display_progress)
}

doVB_pois_offset_sp <- function(N, yv, yi, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_offset_sp`, N, yv, yi, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress)
}

doVB_pois_offset <- function(y, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_offset`, y, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress)
}

myprod <- function(N, xi, xp, lam) {
    .Call(`_moltenNMF_myprod`, N, xi, xp, lam)
}

summyprod <- function(n, xi, xp, lam) {
    .Call(`_moltenNMF_summyprod`, n, xi, xp, lam)
}

myprod_r <- function(N, xj, xp, lam) {
    .Call(`_moltenNMF_myprod_r`, N, xj, xp, lam)
}

myprod_r_i <- function(N, xj, xp, id, lam) {
    .Call(`_moltenNMF_myprod_r_i`, N, xj, xp, id, lam)
}

NegBin_lp <- function(y, np, xi, xp, alpha, beta, tau) {
    .Call(`_moltenNMF_NegBin_lp`, y, np, xi, xp, alpha, beta, tau)
}

Poisson_lp <- function(y, np, xi, xp, alpha, beta) {
    .Call(`_moltenNMF_Poisson_lp`, y, np, xi, xp, alpha, beta)
}

PoissonGamma_rng <- function(N, np, xi, xp, alpha, beta) {
    .Call(`_moltenNMF_PoissonGamma_rng`, N, np, xi, xp, alpha, beta)
}

NegbinGamma_rng <- function(N, np, xi, xp, alpha, beta, tau) {
    .Call(`_moltenNMF_NegbinGamma_rng`, N, np, xi, xp, alpha, beta, tau)
}

