# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bin <- function(filepath_x, filepath_y, bag, n_dim) {
    .Call(`_moltenNMF_read_bin`, filepath_x, filepath_y, bag, n_dim)
}

writeBinaryVec <- function(data, filepath) {
    invisible(.Call(`_moltenNMF_writeBinaryVec`, data, filepath))
}

writeBinaryFile_umat <- function(data, filepath) {
    invisible(.Call(`_moltenNMF_writeBinaryFile_umat`, data, filepath))
}

doVB_negbin <- function(y, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_negbin`, y, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois <- function(y, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois`, y, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois_sp <- function(N, yv, yi, xi, xp, varind, D, L, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_sp`, N, yv, yi, xi, xp, varind, D, L, iter, a, b, V, display_progress)
}

doVB_pois_2D <- function(V, y, rowi, coli, dims, L, iter, a, b, display_progress) {
    .Call(`_moltenNMF_doVB_pois_2D`, V, y, rowi, coli, dims, L, iter, a, b, display_progress)
}

doVB_pois_2D_ww <- function(V, y, rowi, coli, dims, L, iter, weight, a, b, display_progress) {
    .Call(`_moltenNMF_doVB_pois_2D_ww`, V, y, rowi, coli, dims, L, iter, weight, a, b, display_progress)
}

doVB_pois_s_2D <- function(y, rowi, coli, L, iter, subiter, a, b, N1, Nr, Nc, bsize, lr_param, lr_type, display_progress) {
    .Call(`_moltenNMF_doVB_pois_s_2D`, y, rowi, coli, L, iter, subiter, a, b, N1, Nr, Nc, bsize, lr_param, lr_type, display_progress)
}

doVB_pois_s_2D_ww <- function(y, rowi, coli, L, iter, subiter, weight, a, b, N1, Nr, Nc, bsize, lr_param, lr_type, display_progress) {
    .Call(`_moltenNMF_doVB_pois_s_2D_ww`, y, rowi, coli, L, iter, subiter, weight, a, b, N1, Nr, Nc, bsize, lr_param, lr_type, display_progress)
}

doVB_pois_offset_sp <- function(N, yv, yi, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_offset_sp`, N, yv, yi, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress)
}

doVB_pois_offset <- function(y, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress) {
    .Call(`_moltenNMF_doVB_pois_offset`, y, xi, xp, varind, D, L, tau, iter, a, b, V, display_progress)
}

myprod <- function(N, xi, xp, lam) {
    .Call(`_moltenNMF_myprod`, N, xi, xp, lam)
}

summyprod <- function(n, xi, xp, lam) {
    .Call(`_moltenNMF_summyprod`, n, xi, xp, lam)
}

NegBin_lp <- function(y, np, xi, xp, alpha, beta, tau) {
    .Call(`_moltenNMF_NegBin_lp`, y, np, xi, xp, alpha, beta, tau)
}

Poisson_lp <- function(y, np, xi, xp, alpha, beta) {
    .Call(`_moltenNMF_Poisson_lp`, y, np, xi, xp, alpha, beta)
}

PoissonGamma_rng <- function(N, np, xi, xp, alpha, beta) {
    .Call(`_moltenNMF_PoissonGamma_rng`, N, np, xi, xp, alpha, beta)
}

NegbinGamma_rng <- function(N, np, xi, xp, alpha, beta, tau) {
    .Call(`_moltenNMF_NegbinGamma_rng`, N, np, xi, xp, alpha, beta, tau)
}

